Update ubuntu.yml

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -1,12 +1,67 @@
-name: larix Python Package using Conda
+# Compile project on Ubuntu
+name: Ubuntu
 
-on: [push]
+on:
+  push:
+    paths:
+      - "**"
+      - "!.github/**"
+      - ".github/workflows/Ubuntu.yml"
+  # pull_request:
+  #   paths:
+  #     - "**"
+  #     - "!.github"
+  #     - ".github/workflows/Ubuntu.yml"
 
 jobs:
-  build-linux:
-    runs-on: ubuntu-latest
+  build:
+    runs-on: ${{ matrix.os }}
     strategy:
-      max-parallel: 5
+      fail-fast: false
+      # explicit include-based build matrix, of known valid options
+      matrix:
+        include:
+          # 18.04 supports CUDA 10.1+ (gxx <= 8)
+          - os: ubuntu-18.04
+            cuda: "11.0"
+            gcc: 8
+          - os: ubuntu-18.04
+            cuda: "10.2"
+            gcc: 8
+          - os: ubuntu-18.04
+            cuda: "10.1"
+            gcc: 8
+
+          # 16.04 supports CUDA 8+
+          - os: ubuntu-16.04
+            cuda: "11.0"
+            gcc: 7
+          # - os: ubuntu-16.04
+          #   cuda: "10.2"
+          #   gcc: 7
+          # - os: ubuntu-16.04
+          #   cuda: "10.1"
+          #   gcc: 7
+          - os: ubuntu-16.04
+            cuda: "10.0"
+            gcc: 7
+          - os: ubuntu-16.04
+            cuda: "9.2"
+            gcc: 7
+          - os: ubuntu-16.04
+            cuda: "9.1"
+            gcc: 6
+          - os: ubuntu-16.04
+            cuda: "9.0"
+            gcc: 6
+
+          # Libraries-dev subpackage does not exist for CUDA 8. Should make a better way of providing version specific subpackages.
+          # - os: ubuntu-16.04
+          #   cuda: "8.0"
+          #   gcc: 6
+    env:
+      build_dir: "build"
+      config: "Release"
 
     steps:
     - uses: actions/checkout@v2
@@ -27,14 +82,48 @@ jobs:
         $CONDA/bin/flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
     - name: Install required conda packages
       run: |
-        conda install --yes numpy conda-build anaconda-client setuptools cython cmake cudatoolkit=10.1
-    - name: Install cudatoolkit-dev
+        conda install --yes numpy conda-build anaconda-client setuptools cython cmake 
+    - name: Install CUDA
+      env:
+        cuda: ${{ matrix.cuda }}
       run: |
-        conda config --add channels conda-forge
-        conda install --yes cudatoolkit-dev       
+        source ./scripts/actions/install_cuda_ubuntu.sh
+        if [[ $? -eq 0 ]]; then
+          # Set paths for subsequent steps, using ${CUDA_PATH}
+          echo "Adding CUDA to CUDA_PATH, PATH and LD_LIBRARY_PATH"
+          echo "CUDA_PATH=${CUDA_PATH}" >> $GITHUB_ENV
+          echo "${CUDA_PATH}/bin" >> $GITHUB_PATH
+          echo "LD_LIBRARY_PATH=${CUDA_PATH}/lib:${LD_LIBRARY_PATH}" >> $GITHUB_ENV
+        fi
+      shell: bash
+
+    # Specify the correct host compilers
+    - name: Install/Select gcc and g++ 
+      run: |
+        sudo apt-get install -y gcc-${{ matrix.gcc }} g++-${{ matrix.gcc }}
+        echo "CC=/usr/bin/gcc-${{ matrix.gcc }}" >> $GITHUB_ENV
+        echo "CXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+        echo "CUDAHOSTCXX=/usr/bin/g++-${{ matrix.gcc }}" >> $GITHUB_ENV
+    - name: Configure cmake
+      id: configure
+      run: cmake . -B ${{ env.build_dir }} -DCMAKE_BUILD_TYPE=${{ env.config }}
+
+    - name: Configure Error Processing
+      if: ${{ failure() && steps.configure.outcome == 'failure' }}
+      working-directory: ${{ env.build_dir }}
+      run: |
+          if [[ -f "CMakeFiles/CMakeOutput.log" ]]; then
+            echo "---- CMakeFiles/CMakeOutput.log"
+            cat CMakeFiles/CMakeOutput.log
+            echo "----"
+          fi
+          if [[ -f "CMakeFiles/CMakeError.log" ]]; then
+            echo "---- CMakeFiles/CMakeError.log"
+            cat CMakeFiles/CMakeError.log
+            echo "----"
+          fi
     - name: checking installed packages
       run: |        
         conda info
         conda list
-        nvcc --version
-        
+        nvcc --version       
